# Generated by Django 2.1.2 on 2018-10-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import issues.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=issues.models.IssueState)),
                ('category', django_enumfield.db.fields.EnumField(default=0, enum=issues.models.IssueState)),
                ('solver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solver', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
