# Generated by Django 2.1.2 on 2018-10-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20181004_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='finished',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
