# Generated by Django 2.1.2 on 2018-10-15 11:40

from django.db import migrations, models
import django_enumfield.db.fields
import issues.models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20181004_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='duration',
            field=models.DurationField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=django_enumfield.db.fields.EnumField(default=0, enum=issues.models.IssueCategory),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
